export const keys = {
  GOOGLE_API: process.env.REACT_APP_GOOGLE_API,
  CLOUDINARY_KEY: process.env.REACT_APP_CLOUDINARY_KEY,
  CLOUDINARY_PRESET: process.env.REACT_APP_CLOUDINARY_PRESET,
  GOOGLE_OAUTH: process.env.REACT_APP_GOOGLE_OAUTH,
  FACEBOOK_OAUTH_URL: process.env.REACT_APP_FACEBOOK_OAUTH_URL,
  STRIPE_KEY: process.env.REACT_APP_STRIPE_KEY,
  ZENDESK_KEY: process.env.REACT_APP_ZENDESK_KEY,
};
